### PR TITLE
Feature/rename package metadata files

### PR DESCRIPTION
**Pull request by brastak**
For #27 - rename package metadata files

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#29](https://github.com/artipie/npm-proxy-adapter/issues/29) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/bdea2371-73eb-40e0-91ee-7ca18849ab93); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/artipie/npm-proxy-adapter/issues/29#issuecomment-634571741))

@g4s8 This pull request [#29](https://github.com/artipie/npm-proxy-adapter/issues/29) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d565047f-4ced-42c7-a81c-7e1b89ad5a19); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by brastak** [comment]
@carlosmiranda there was some confusion with this Pull Request - I have created a series of PRs yesterday that should be merged one-by-one. And to prevent early review I put later PRs on Draft status. But zerocrat ignores the statuses, so you really have reviewed this set of changes in the #31 

You can re-review it if you want, or I can close this PR and all changes will be merged w/ #31

**Comment by carlosmiranda** [comment]
@brastak yeah I think it makes sense to just do it in #31.

**Comment by brastak** [comment]
Close, because of changes were reviewed in #31

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#29` is not assigned, can't get performer

**Pull request closed without merging**
