### PR TITLE
Extract NPM proxy storage from NPM proxy class to encapsulate storage…

### PR DESCRIPTION
**Pull request by brastak**
For #6

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#12](https://github.com/artipie/npm-proxy-adapter/issues/12) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ff5fcbcf-b53a-4e3e-8a74-a80a67deb3b7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/12#issuecomment-617386566))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#12](https://github.com/artipie/npm-proxy-adapter/issues/12), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/12#issuecomment-617386566))

@Vatavuk Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#12](https://github.com/artipie/npm-proxy-adapter/issues/12) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/777e0634-0c5a-450d-8430-148f62231822); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Review by HDouss — CHANGES_REQUESTED** [review]
@brastak Shouldn't we have an NpmProxyStorage testing class? or extracting storage testing logic to a NpmProxyStorageTest class?

**Comment by brastak** [comment]
@HDouss added tests, please see update

**Review by HDouss — DISMISSED** [review]
@brastak Thanks

**Comment by HDouss** [comment]
@g4s8 Please review or merge.

**Comment by g4s8** [comment]
@brastak please check build logs: some tests failed

**Comment by brastak** [comment]
@g4s8 It's port busy issue. random ports is introduced in https://github.com/artipie/npm-proxy-adapter/pull/10, not merged yet. My local branch build works fine. I think, if you re-run tests, it will succeeded

**Comment by brastak** [comment]
@g4s8 I finally found out the reason on failing tests and fixed it. ready to merge

**Review by g4s8 — APPROVED** [review]
@brastak please try to make smaller PR next time, it will be easier to review, and it can be merged faster

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@HDouss please make sure you will find at least 3 issues during next CR, thanks

**Comment by HDouss** [comment]
@sereshqua Yes sure.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
